version = 0.1

[default.deploy.parameters]
stack_name = "chat-colaborativo-serverless"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "chat-colaborativo-serverless"
